name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/elixir-lint-local.yml
    with:
      otp_version: "27.2.1"
      elixir_version: "1.18.2"
      lint_command: mix format --check-formatted && mix compile --warnings-as-errors && mix credo --min-priority higher

  test:
    name: Test
    uses: agentjido/github-actions/.github/workflows/elixir-test.yml@33a4f1143b681c26be9b68d5e8feb74dfce4083c
    with:
      otp_versions: '["27.2.1"]'
      elixir_versions: '["1.18.2"]'
      test_command: mix test
      postgres: true
      postgres_image: pgvector/pgvector:pg16
